### ISSUE TITLE
Ruby 2.7 support is broken

### ISSUE THREAD

**Issue by biow0lf** [github/actionview-component#221]
### Steps to reproduce

/app/components/character_employment_history_row_component.rb

```ruby
class CharacterEmploymentHistoryRowComponent < ActionView::Component::Base
  attr_reader :corporation, :start_date

  def initialize(corporation:, start_date:)
    @corporation = corporation
    @start_date = start_date
  end
end
```

/app/components/character_employment_history_row_component.html.erb

```erb
Anything
```

### Expected behavior

Component render

### Actual behavior

Could not find a template file for CharacterEmploymentHistoryRowComponent. excluded from capture: DSN not set
  
ActionView::Template::Error (Could not find a template file for CharacterEmploymentHistoryRowComponent.):

### System configuration

**Rails version**:

GIT
  remote: https://github.com/rails/rails.git
  revision: eef309eb6dda64fe39e51daa408c91f793cd17e7
  branch: 6-0-stable

(Current 6-0-stable)

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**Gem version**: actionview-component (1.11.1)

### Workaround

If `const_source_location_supported?` return false, everything rendered. Looks like `const_source_location(self.name)[0]` return something unexpected.

**Comment by joelhawksley** [comment]
@dylnclrk might you be able to look at this?

**Comment by dylnclrk** [comment]
@biow0lf thanks for the bug report!

In this case, what’s returned by `const_source_location`? is it nil? some other sort of object?

Everything you’re doing seems to match the setup in the tests for this feature. 

Can you reproduce this error in a demo repository?

**Comment by biow0lf** [comment]
Demo: https://github.com/biow0lf/actionview-component-issues-221

Just open "/".

**Comment by rmacklin** [comment]
After applying this patch to [opt out of the `zeitwerk` autoloader](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#opting-out) in the `actionview-component-issues-221` repo
```diff
diff --git a/config/application.rb b/config/application.rb
index 91b4539..b4ec846 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -11,6 +11,7 @@ module ActionviewComponentIssues221
   class Application < Rails::Application
     # Initialize configuration defaults for originally generated Rails version.
     config.load_defaults 6.0
+    config.autoloader = :classic
 
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration can go into files in config/initializers

```
the application works (this error doesn't get raised).

Similarly, applying this patch in the `actionview-component` repo (which enables `zeitwerk`)
```diff
diff --git a/test/config/application.rb b/test/config/application.rb
index 683bac9..510c7dc 100644
--- a/test/config/application.rb
+++ b/test/config/application.rb
@@ -14,6 +14,7 @@ require "slim"
 
 module Dummy
   class Application < Rails::Application
+    config.load_defaults 6.0
     config.action_controller.asset_host = "http://assets.example.com"
   end
 end

```
causes the test suite to fail on ruby 2.7.0.

An alternative patch (without opting out of `zeitwerk`) that makes the `actionview-component-issues-221` application work is:
```diff
diff --git a/config/environment.rb b/config/environment.rb
index 426333b..dd6c15b 100644
--- a/config/environment.rb
+++ b/config/environment.rb
@@ -3,3 +3,5 @@ require_relative 'application'
 
 # Initialize the Rails application.
 Rails.application.initialize!
+
+require_relative '../app/components/character_employment_history_row_component'

```

So it seems that ruby 2.7 support is specifically broken for with applications using the `zeitwerk` autoloader.

**Comment by joelhawksley** [comment]
@rmacklin thanks for the diagnosis. Given that constraint, I'm wondering if we should just revert the 2.7-specific behavior. What do you think?

**Comment by rmacklin** [comment]
It seems like at least in the short-term, reverting would be fine. But it's still probably worth figuring out if this is revealing a bug in either `zeitwerk` or in ruby 2.7's `const_source_location` method. (It's also possible this is "expected behavior", but in that case it may be worth documenting as a potential caveat when using `zeitwerk`.)

I am not familiar with the `const_source_location` method, but here's what [its docs](https://ruby-doc.org/core-2.7.0/Module.html#method-i-const_source_location) say:
> Returns the Ruby source filename and line number containing first definition of constant specified. If the named constant is not found, nil is returned. If the constant is found, but its source location can not be extracted (constant is defined in C code), empty array is returned.

What appears to be happening is:
- At the time the ruby interpreter is evaluating the reference to `CharacterEmploymentHistoryRowComponent` in this line:
  https://github.com/biow0lf/actionview-component-issues-221/blob/11fa161394f2b2b537f6696eb51a6b64b0e9abc9/app/views/welcome/index.html.erb#L4 the `CharacterEmploymentHistoryRowComponent` constant has not been defined.
- The autoloader kicks in, finds `app/components/character_employment_history_row_component.rb`, and evaluates it, which defines the `CharacterEmploymentHistoryRowComponent` constant.
- Because of this dynamic process, ruby gets "tricked" into thinking that line in `app/views/welcome/index.html.erb` is where `CharacterEmploymentHistoryRowComponent` is defined.
- However, if you use the final patch in https://github.com/github/actionview-component/issues/221#issuecomment-589842256 then `app/components/character_employment_history_row_component.rb` is explicitly `require`d before ruby evaluates `app/views/welcome/index.html.erb` and therefore it can correctly determine the line that actually defines `CharacterEmploymentHistoryRowComponent`.

It might be worthwhile to loop in @fxn (the author of `zeitwerk`)...

**Comment by jonspalmer** [comment]
My sense is either the example or the gem or both are "doing autoloading wrong" wrt Ruby 2.7. I remember there being a bunch of documentation around those details in the upgrade guides.

**Comment by jonspalmer** [comment]
I did a little digging the problem isn't that ruby thinks that CharacterEmploymentHistoryRowComponent is defined in the erb file. The problem is that it thinks its defined in "lib/zeitwerk/loader.rb", 351

I'm a little suspicious that the new `const_source_location` doesn't actually behave the ways we want with zeitwerk loading. It would be great fo @fxn to chime in.

**Comment by rmacklin** [comment]
> the problem isn't that ruby thinks that CharacterEmploymentHistoryRowComponent is defined in the erb file. The problem is that it thinks its defined in "lib/zeitwerk/loader.rb", 351

That's not what I'm seeing. If I apply this patch to the `actionview-component-issues-221` repo (which monkey patches [`ActionView::Component::Base::source_location`](https://github.com/github/actionview-component/blob/v1.11.0/lib/action_view/component/base.rb#L143-L153) to print the value of `const_source_location(self.name)` and adds a test to reproduce the bug):
```diff
diff --git a/config/environment.rb b/config/environment.rb
index 426333b..cc107fa 100644
--- a/config/environment.rb
+++ b/config/environment.rb
@@ -3,3 +3,25 @@ require_relative 'application'
 
 # Initialize the Rails application.
 Rails.application.initialize!
+
+module ActionView
+  module Component
+    class Base
+      class << self
+        def source_location
+          @source_location ||=
+              if const_source_location_supported?
+                puts 'const_source_location(self.name).inspect:'
+                puts const_source_location(self.name).inspect
+                const_source_location(self.name)[0]
+              else
+                # Require `#initialize` to be defined so that we can use `method#source_location`
+                # to look up the filename of the component.
+                initialize_method = instance_method(:initialize)
+                initialize_method.source_location[0] if initialize_method.owner == self
+              end
+        end
+      end
+    end
+  end
+end
diff --git a/test/controllers/welcome_controller_test.rb b/test/controllers/welcome_controller_test.rb
new file mode 100644
index 0000000..37c86d4
--- /dev/null
+++ b/test/controllers/welcome_controller_test.rb
@@ -0,0 +1,9 @@
+require 'test_helper'
+
+class WelcomeControllerTest < ActionDispatch::IntegrationTest
+  test "index" do
+    get root_url
+
+    assert_response :ok
+  end
+end

```

and then run that test:
```
bundle
bundle exec rails db:create db:migrate
bundle exec ruby -Itest test/controllers/welcome_controller_test.rb
```
it prints:

```
const_source_location(self.name).inspect:
["/Users/rmacklin/src/github.com/biow0lf/actionview-component-issues-221/app/views/welcome/index.html.erb", 4]
```

**Comment by jonspalmer** [comment]
Fascinating. Seems like we have work to do to figure this out. Seems like we should revert until we have this figured out.

**Comment by fxn** [comment]
Hey, these days I am very busy working on a talk. Glad to help whenever I have the time.

I am not sure I understand the description. Is it saying that if the template has an error (unknown constant `Anything`), the expected behaviour is to get it rendered? Or does "Anything" mean "any valid content"?

**Comment by jonspalmer** [comment]
@joelhawksley Curious about the origin of using `source_location` to determine the view location. I don't think Rails does it that way for determining views for controllers. Why cab't we just use the namespace of the Component to deduce the view locations?

**Comment by rmacklin** [comment]
@fxn, thanks for taking a look! I think "Anything" in the first post of this thread was a stub for "any content", but I think reading just that example is probably not very helpful - it'll be easier if you can reference the example application in the https://github.com/biow0lf/actionview-component-issues-221 repo.

What we're seeing in that application is that when it's using `zeitwerk`, the return value of ruby 2.7's `const_source_location` method is the location of the first reference to the constant (`CharacterEmploymentHistoryRowComponent`), rather than the location of the definition of that constant. When `zeitwerk` is disabled in favor of the `classic` autoloader, the return value of `const_source_location` is (correctly) the definition of the `CharacterEmploymentHistoryRowComponent` constant. I provided a bit more detail of my findings in https://github.com/github/actionview-component/issues/221#issuecomment-589842256, https://github.com/github/actionview-component/issues/221#issuecomment-589859911, https://github.com/github/actionview-component/issues/221#issuecomment-589896879.

**Comment by joelhawksley** [comment]
> @joelhawksley Curious about the origin of using `source_location` to determine the view location. I don't think Rails does it that way for determining views for controllers. Why cab't we just use the namespace of the Component to deduce the view locations?

@jonspalmer it's been a while since I've looked at this part of the library in depth, but you raise a fair question. I'd love to see a spike PR for going that route 😄.

**Comment by dark-panda** [comment]
Adding this here, this is what we currently use in our `ApplicationComponent` to avoid having to specify `#initialize` and also to move our views path. Our devs wanted to avoid mixing our Haml files with the Ruby files, so we put our views into `app/components/views` and the component definitions themselves into `app/components`. This seems to work fine in our case and all tests are passing without modification.

```ruby
def source_location
  @source_location ||= Rails.root.join("app/components/#{name.underscore}.rb").to_s
end

def matching_views_in_source_location
  return [] unless source_location

  Dir.glob(
    Pathname.new(source_location)
      .sub('/app/components/', '/app/components/views/')
      .sub_ext(".*{#{ActionView::Template.template_handler_extensions.join(',')}}")
  ) - [source_location]
end
```

Of course, this does hardcode the paths we use, but this could be extended to make the paths configurable as necessary. At any rate, this Works For Us™.
