### ISSUE TITLE
Want to use Action Pack Variants.

### ISSUE THREAD

**Issue by kenzooooo** [github/actionview-component#34]
If variants can be used, more uses.

for example

```
app/components/article_component.html.erb
app/components/article_component.html+amp.erb
app/components/article_component.html+sp.erb
app/components/article_component.rb
```

Currently only one view is supported.

Really please.

**Comment by joelhawksley** [comment]
@kenzooooo thank you for the suggestion! While we aren't planning to work on support for variants in the near future, I have no objection to supporting them. 

I'd happily accept a PR 😄

**Comment by juanmanuelramallo** [comment]
@joelhawksley I've been trying to solve this, but with not much success 🙈 

The lookup_context variable has the `variants` method which returns an array of variants from the request, so that's ok. I also managed to update the `compiled_template` and `template_file_path` methods to receive a variant name as an argument. That works fine, I added some tests, **but I'm not sure how to update the class_eval that implements the `call` method**.

So I already have it working for first time requests, but as soon as you start using already compiled templates, you see that the request returns the previous used variant. And this is because I couldn't come up with a way to update the `call` method to actually return the variant requested.

**Do you have some ideas regarding this?**

Maybe I'm tackling this wrong? It felt so more complicated than it actually appears to be.
Thanks in advance!
